# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GoogleBookAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleBookAPI
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 4.5'
pod 'AlamofireImage'

end
